[build]
command = "python build_netlify.py"
publish = "dist"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.10"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.obj"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
